# Generated by Django 4.1.7 on 2023-06-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_abc_app', '0018_alter_abc_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abc',
            name='a',
            field=models.IntegerField(default=0, verbose_name='Значение X'),
        ),
        migrations.AlterField(
            model_name='abc',
            name='b',
            field=models.IntegerField(default=0, help_text='Подсказка для поля Y', verbose_name='Значение Y'),
        ),
        migrations.AlterField(
            model_name='abc',
            name='c',
            field=models.IntegerField(choices=[(0, 'ноль'), (10, 'десять'), (15, 'пятнадцать'), (20, 'двадцать')], default=0, verbose_name='Значение Z'),
        ),
        migrations.AlterField(
            model_name='abc',
            name='task',
            field=models.CharField(default='1/(XY) равно ?', max_length=255, verbose_name='Формулировка  задачи'),
        ),
    ]
